services:
  ldap:
    restart: unless-stopped
    image: 389ds/dirsrv:2.4
    hostname: ldap
    volumes:
      - ldap:/data
    environment:
      DS_DM_PASSWORD: '123456'
    ports:
      - "636:3636"
      - "389:3389"
    networks:
      - ldap
  ldap-init:
    restart: no
    image: ghcr.io/patrick8079/container-389ds-init:main
    hostname: ldap-init
    volumes:
      - ldap:/data
    environment:
      DS_INIT_BIND_DN_PASSWORD: 123456
      DS_INIT_TARGET_HOST: ldap
      DS_INIT_PORT: 3389
      DS_INIT_PROTOCOL: ldap
      DS_INIT_SUFFIX_NAME: dc=example,dc=com
      DS_INIT_BE_NAME: userRoot
    entrypoint: /root/init.sh
    depends_on:
      ldap:
        condition: "service_started"
    networks:
      - ldap
volumes:
  ldap:
networks:
  ldap:
    driver: bridge