services:
  ldap:
    restart: unless-stopped
    image: 389ds/dirsrv:2.4
    hostname: ldap
    volumes:
      - ldap:/data
    env_file: ".ldap.env"
    ports:
      - "636:3636"
      - "389:3389"
  ldap-init:
    restart: no
    image: ghcr.io/patrick8079/container-389ds-init:main
    hostname: ldap-init
    volumes:
      - ldap:/data
    env_file: ".ldap-init.env"
    entrypoint: /root/init.sh
    depends_on:
      ldap:
        condition: "service_started"
volumes:
  ldap: