apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ldap-init
  name: ldap-init
spec:
  containers:
    - command:
        - /root/init.sh
      env:
        - name: DS_INIT_BE_NAME
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_BE_NAME
              name: ldap-init-env
        - name: DS_INIT_BIND_DN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_BIND_DN_PASSWORD
              name: ldap-init-env
        - name: DS_INIT_PORT
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_PORT
              name: ldap-init-env
        - name: DS_INIT_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_PROTOCOL
              name: ldap-init-env
        - name: DS_INIT_SUFFIX_NAME
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_SUFFIX_NAME
              name: ldap-init-env
        - name: DS_INIT_TARGET_HOST
          valueFrom:
            configMapKeyRef:
              key: DS_INIT_TARGET_HOST
              name: ldap-init-env
      image: ghcr.io/patrick8079/container-389ds-init:main
      name: ldap-init
      volumeMounts:
        - mountPath: /data
          name: ldap
  hostname: ldap-init
  restartPolicy: Never
  volumes:
    - name: ldap
      persistentVolumeClaim:
        claimName: ldap
