apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ldap
  name: ldap
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
