apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ldap
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ldap
    spec:
      containers:
        - env:
            - name: DS_DM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DS_DM_PASSWORD
                  name: ldap-env
          image: 389ds/dirsrv:2.4
          name: ldap
          ports:
            - containerPort: 3636
              protocol: TCP
            - containerPort: 3389
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: ldap
      hostname: ldap
      restartPolicy: Always
      volumes:
        - name: ldap
          persistentVolumeClaim:
            claimName: ldap
